image: nfcore/gitpod:latest

tasks:
  - name: Initialize
    init: |
      pip install graphviz snakemake fastq-dl pysradb
      . /opt/conda/etc/profile.d/conda.sh
      conda activate base
      conda create -n jupyter -y -q jupyter
      #bash test.data.sh
